### ISSUE TITLE
wrong data type?

### ISSUE THREAD

**Issue by tetzlav** [hacki11/ioBroker.bsblan#48]
With host adapter v3.3.X i get following infos/warnings:

<html><body>

bsblan.0 | 2021-05-07 11:16:13.786 | info | (22540) State value to set for "bsblan.0.Außentemperatur_(10003)" has to be type "number" but received type "string"
-- | -- | -- | --
bsblan.0 | 2021-05-07 11:16:13.786 | info | (22540) State value to set for "bsblan.0.Raumtemperatur_1_(10000)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.786 | info | (22540) State value to set for "bsblan.0.Wasserdruck_H3_(9009)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.786 | info | (22540) State value to set for "bsblan.0.Schienenvorlauftemperatur_(8950)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.786 | info | (22540) State value to set for "bsblan.0.Trinkwassertemperatur_1_(8830)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.786 | info | (22540) State value to set for "bsblan.0.Mod_Pumpe_Sollwert_(8750)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.785 | info | (22540) State value to set for "bsblan.0.Vorlaufsollwert_1_(8744)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.785 | info | (22540) State value to set for "bsblan.0.Raumtemperatur_1_(8740)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.785 | info | (22540) State value to set for "bsblan.0.Außentemperatur_gemischt_(8704)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.745 | info | (22540) State value to set for "bsblan.0.Außentemperatur_gedämpft_(8703)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.745 | info | (22540) State value to set for "bsblan.0.Außentemperatur_(8700)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.744 | info | (22540) State value to set for "bsblan.0.Startzähler_1Stufe_(8331)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.744 | info | (22540) State value to set for "bsblan.0.Brennermodulation_(8326)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.744 | info | (22540) State value to set for "bsblan.0.Gebläsedrehzahl_(8323)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.744 | info | (22540)  State value to set for "bsblan.0.Kesselrücklauftemperatur_Ist_(8314)"  has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.744 | info | (22540) State value to set for "bsblan.0.Kesseltemperatur_(8310)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.744 | info | (22540) State value to set for "bsblan.0.Drehzahl_Kesselpumpe_(8308)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.744 | info | (22540) State value to set for "bsblan.0.Fühlertemperatur_BX1_(7820)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.744 | info | (22540) State value to set for "bsblan.0.Korrektur_Außenfühler_(6100)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.743 | info | (22540) State value to set for "bsblan.0.Raumeinfluss_(750)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.743 | info | (22540) State value to set for "bsblan.0.Kennlinie_Steilheit_(720)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:13.743 | info | (22540) State value to set for "bsblan.0.Komfortsollwert_(710)" has to be type "number" but received type "string"
bsblan.0 | 2021-05-07 11:16:07.091 | warn | (22540) State "bsblan.0.Außentemperatur_(10003)" has no existing object, this might lead to an error in future versions
bsblan.0 | 2021-05-07 11:16:07.091 | warn | (22540) State "bsblan.0.Raumtemperatur_1_(10000)" has no existing object, this might lead to an error in future versions
bsblan.0 | 2021-05-07 11:16:07.088 | info | (22540) Connection established successfully
bsblan.0 | 2021-05-07 11:16:07.088 | info | (22540) Setup objects done.

</body>
</html>

**Comment by hacki11** [comment]
Can you check if you have a object called
`bsblan.0.Raumtemperatur_1_(10000)` and if you have configured `10000` in instance config?

**Comment by tetzlav** [comment]
Yes, it's configured and the object datapoint exists. I use it to transmit the room temperature.

**Comment by hacki11** [comment]
Can you test the current development branch on your system?
Do you have v1 of bsb lan firmware? Would be good to test backwards compatiblity.
https://github.com/hacki11/ioBroker.bsblan/tree/bsblan-2.x-support

**Comment by tetzlav** [comment]
Yes, i use the v1 of bsb lan (arduino mega) firmware.
I updated the adapter to v0.3.0. But the development version lets the arduino firmware hanging after the first request.



bsblan.0 | 2021-05-19 10:29:59.881 | warn | (28082) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
-- | -- | -- | --
bsblan.0 | 2021-05-19 10:29:59.834 | error | (28082) adapter disabled
bsblan.0 | 2021-05-19 10:29:28.663 | warn | (26124) Terminated (UNCAUGHT_EXCEPTION): Without reason
bsblan.0 | 2021-05-19 10:29:28.662 | info | (26124) terminating
bsblan.0 | 2021-05-19 10:29:28.662 | info | (26124) cleaned everything up...
bsblan.0 | 2021-05-19 10:29:28.660 | error | (26124) Cannot convert undefined or null to object
bsblan.0 | 2021-05-19 10:29:28.660 | error | (26124) TypeError: Cannot convert undefined or null to object     at hasOwnProperty (&lt;anonymous&gt;)     at Bsblan.updateNativeData (/opt/iobroker/node_modules/iobroker.bsblan/main.js:461:39)     at asyn
bsblan.0 | 2021-05-19 10:29:28.660 | error | (26124) unhandled promise rejection: Cannot convert undefined or null to object
bsblan.0 | 2021-05-19 10:29:28.660 | error | (26124)  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
bsblan.0 | 2021-05-19 10:29:28.659 | error | (26124) Connection failed
bsblan.0 | 2021-05-19 10:29:28.659 | error | (26124) RequestError: Error: connect ECONNREFUSED 192.168.178.8:80     at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)     at Request.plumbing.callback (/opt/
bsblan.0 | 2021-05-19 10:29:28.659 | error | (26124) Error: connect ECONNREFUSED 192.168.178.8:80
bsblan.0 | 2021-05-19 10:29:12.566 | info | (26124) Updating Metainformation of Parameters...
bsblan.0 | 2021-05-19 10:29:12.530 | info | (26124)  Values found:  10000,10003,1660,6100,700,710,720,750,7820,8009,8308,8310,8314,8323,8326,8331,8700,8703,8704,8740,8744,8750,8830,8950,9009
bsblan.0 | 2021-05-19 10:29:12.521 | info | (26124) starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.bsblan, node: v12.22.1, js-controller: 3.3.8
bsblan.0 | 2021-05-19 10:28:41.391 | warn | (9299) Terminated (UNCAUGHT_EXCEPTION): Without reason
bsblan.0 | 2021-05-19 10:28:41.391 | info | (9299) terminating
bsblan.0 | 2021-05-19 10:28:41.391 | info | (9299) cleaned everything up...
bsblan.0 | 2021-05-19 10:28:41.388 | error | (9299) Cannot convert undefined or null to object
bsblan.0 | 2021-05-19 10:28:41.388 | error | (9299) TypeError: Cannot convert undefined or null to object     at hasOwnProperty (&lt;anonymous&gt;)     at Bsblan.updateNativeData (/opt/iobroker/node_modules/iobroker.bsblan/main.js:461:39)     at async
bsblan.0 | 2021-05-19 10:28:41.388 | error | (9299) unhandled promise rejection: Cannot convert undefined or null to object
bsblan.0 | 2021-05-19 10:28:41.388 | error | (9299)  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
bsblan.0 | 2021-05-19 10:28:41.387 | error | (9299) Connection failed
bsblan.0 | 2021-05-19 10:28:41.387 | error | (9299) RequestError: Error: ESOCKETTIMEDOUT     at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)     at Request.plumbing.callback (/opt/iobroker/node_modules/r
bsblan.0 | 2021-05-19 10:28:41.385 | error | (9299) Error: ESOCKETTIMEDOUT
bsblan.0 | 2021-05-19 10:21:58.340 | info | (9299) Updating Metainformation of Parameters...
bsblan.0 | 2021-05-19 10:21:58.340 | info | (9299) Migrate bsblan.0.Wasserdruck_H3_(9009): set write = true
bsblan.0 | 2021-05-19 10:21:58.340 | info | (9299) Migrate bsblan.0.Schienenvorlauftemperatur_(8950): set write = true
bsblan.0 | 2021-05-19 10:21:58.340 | info | (9299) Migrate bsblan.0.Trinkwassertemperatur_1_(8830): set write = true
bsblan.0 | 2021-05-19 10:21:58.340 | info | (9299) Migrate bsblan.0.Mod_Pumpe_Sollwert_(8750): set write = true
bsblan.0 | 2021-05-19 10:21:58.340 | info | (9299) Migrate bsblan.0.Vorlaufsollwert_1_(8744): set write = true
bsblan.0 | 2021-05-19 10:21:58.340 | info | (9299) Migrate bsblan.0.Raumtemperatur_1_(8740): set write = true
bsblan.0 | 2021-05-19 10:21:58.340 | info | (9299) Migrate bsblan.0.Außentemperatur_gemischt_(8704): set write = true
bsblan.0 | 2021-05-19 10:21:58.339 | info | (9299) Migrate bsblan.0.Außentemperatur_gedämpft_(8703): set write = true
bsblan.0 | 2021-05-19 10:21:58.339 | info | (9299) Migrate bsblan.0.Außentemperatur_(8700): set write = true
bsblan.0 | 2021-05-19 10:21:58.339 | info | (9299) Migrate bsblan.0.Startzähler_1Stufe_(8331): set write = true
bsblan.0 | 2021-05-19 10:21:58.339 | info | (9299) Migrate bsblan.0.Brennermodulation_(8326): set write = true
bsblan.0 | 2021-05-19 10:21:58.339 | info | (9299) Migrate bsblan.0.Gebläsedrehzahl_(8323): set write = true
bsblan.0 | 2021-05-19 10:21:58.339 | info | (9299) Migrate bsblan.0.Kesselrücklauftemperatur_Ist_(8314): set write = true
bsblan.0 | 2021-05-19 10:21:58.339 | info | (9299) Migrate bsblan.0.Kesseltemperatur_(8310): set write = true
bsblan.0 | 2021-05-19 10:21:58.339 | info | (9299) Migrate bsblan.0.Drehzahl_Kesselpumpe_(8308): set write = true
bsblan.0 | 2021-05-19 10:21:58.339 | info | (9299) Migrate bsblan.0.Status_Brenner_(8009): set write = true
bsblan.0 | 2021-05-19 10:21:58.338 | info | (9299) Migrate bsblan.0.Fühlertemperatur_BX1_(7820): set write = true
bsblan.0 | 2021-05-19 10:21:58.304 | info | (9299)  Values found:  10000,10003,1660,6100,700,710,720,750,7820,8009,8308,8310,8314,8323,8326,8331,8700,8703,8704,8740,8744,8750,8830,8950,9009
bsblan.0 | 2021-05-19 10:21:58.295 | info | (9299) starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.bsblan, node: v12.22.1, js-controller: 3.3.8

`GET /JC=700,710,720,750,1660,6100,7820,8009,8308,8310,8314,8323,8326,8331,8700,8703,8704,8740,8744,8750,8830,8950,9009,10000,10003 HTTP/1.1
/JC=700,710,720,750,1660,6100,7820,8009,8308,8310,8314,8323,8326,8331,8700,8703,8704,8740,8744,8750,8830,8950,9009,10000,10003`

and nothing more in serial log....

**Comment by hacki11** [comment]
The error in the log should be fixed now

**Comment by tetzlav** [comment]
The bsb-lan adapter v1 still hangs after first request with https://github.com/hacki11/ioBroker.bsblan/tree/bsblan-2.x-support.

**Comment by hacki11** [comment]
Can you change the log level to debug and attach the log file=

**Comment by tetzlav** [comment]
>2021-05-26 09:35:34.949  - info: host.omv iobroker Update "system.adapter.bsblan.0"
2021-05-26 09:35:34.954  - info: host.omv stopInstance system.adapter.bsblan.0 (force=false, process=true)
2021-05-26 09:35:34.955  - info: bsblan.0 (25085) Got terminate signal TERMINATE_YOURSELF
2021-05-26 09:35:34.956  - info: bsblan.0 (25085) cleaned everything up...
2021-05-26 09:35:34.956  - info: bsblan.0 (25085) terminating
2021-05-26 09:35:34.956  - info: bsblan.0 (25085) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-05-26 09:35:34.997  - info: host.omv stopInstance system.adapter.bsblan.0 send kill signal
2021-05-26 09:35:35.537  - info: host.omv instance system.adapter.bsblan.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-05-26 09:35:35.964  - info: host.omv iobroker exit 0
2021-05-26 09:35:38.034  - info: host.omv instance system.adapter.bsblan.0 started with pid 29395
2021-05-26 09:35:38.371  - debug: bsblan.0 (29395) Redis Objects: Use Redis connection: 0.0.0.0:9001
2021-05-26 09:35:38.379  - debug: bsblan.0 (29395) Objects client ready ... initialize now
2021-05-26 09:35:38.380  - debug: bsblan.0 (29395) Objects create System PubSub Client
2021-05-26 09:35:38.380  - debug: bsblan.0 (29395) Objects create User PubSub Client
2021-05-26 09:35:38.380  - debug: bsblan.0 (29395) Objects client initialize lua scripts
2021-05-26 09:35:38.385  - debug: bsblan.0 (29395) Objects connected to redis: 0.0.0.0:9001
2021-05-26 09:35:38.387  - debug: bsblan.0 (29395) objectDB connected
2021-05-26 09:35:38.387  - debug: bsblan.0 (29395) Redis States: Use Redis connection: 0.0.0.0:9000
2021-05-26 09:35:38.392  - debug: bsblan.0 (29395) States create System PubSub Client
2021-05-26 09:35:38.392  - debug: bsblan.0 (29395) States create User PubSub Client
2021-05-26 09:35:38.438  - debug: bsblan.0 (29395) States connected to redis: 0.0.0.0:9000
2021-05-26 09:35:38.438  - debug: bsblan.0 (29395) statesDB connected
2021-05-26 09:35:38.596  - info: bsblan.0 (29395) starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.bsblan, node: v12.22.1, js-controller: 3.3.11
2021-05-26 09:35:38.605  - info: bsblan.0 (29395) Values found: 10000,10003,1660,6100,700,710,720,750,7820,8009,8308,8310,8314,8323,8326,8331,8700,8703,8704,8740,8744,8750,8830,8950,9009
2021-05-26 09:35:38.620  - info: bsblan.0 (29395) Migrate bsblan.0.Fühlertemperatur_BX1_(7820): set write = true
2021-05-26 09:35:38.620  - info: bsblan.0 (29395) Migrate bsblan.0.Status_Brenner_(8009): set write = true
2021-05-26 09:35:38.620  - info: bsblan.0 (29395) Migrate bsblan.0.Drehzahl_Kesselpumpe_(8308): set write = true
2021-05-26 09:35:38.620  - info: bsblan.0 (29395) Migrate bsblan.0.Kesseltemperatur_(8310): set write = true
2021-05-26 09:35:38.620  - info: bsblan.0 (29395) Migrate bsblan.0.Kesselrücklauftemperatur_Ist_(8314): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Gebläsedrehzahl_(8323): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Brennermodulation_(8326): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Startzähler_1Stufe_(8331): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Außentemperatur_(8700): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Außentemperatur_gedämpft_(8703): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Außentemperatur_gemischt_(8704): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Raumtemperatur_1_(8740): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Vorlaufsollwert_1_(8744): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Mod_Pumpe_Sollwert_(8750): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Trinkwassertemperatur_1_(8830): set write = true
2021-05-26 09:35:38.621  - info: bsblan.0 (29395) Migrate bsblan.0.Schienenvorlauftemperatur_(8950): set write = true
2021-05-26 09:35:38.622  - info: bsblan.0 (29395) Migrate bsblan.0.Wasserdruck_H3_(9009): set write = true
2021-05-26 09:35:38.622  - info: bsblan.0 (29395) Updating Metainformation of Parameters...

thats it and bsblan v1 hangs...

**Comment by DominikReber** [comment]
I'm having the same "problem". It works but I am getting a lot of logs like:

`State value to set for "bsblan.0.Raumtemperaturbegrenzung_(760)" has to be type "number" but received type "string"`

Getting it for every value I have configured.

**Comment by Eldarion85** [comment]
I also have the problem that my logging writes these entries with every query.
The adapter works and I get the values, but the entries are still annoying.
What can I do to ensure that the values are sent with the correct data type?

@DominikReber
I only find version 0.2.2 on GitHub and MPM and I installed that too. Where did you get version 0.3.0 from?

![BSB](https://user-images.githubusercontent.com/90176159/160072252-51912ec6-7d14-4e89-86b1-d5acc5705b7f.jpg)
